name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: macos-14 # 使用具体的 macOS 版本
    strategy:
      matrix:
        arch: [arm64] # 只构建 ARM64 架构

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          architecture: ${{ matrix.arch }} # 设置架构

      - name: Install dependencies
        run: pnpm install

      - name: Build for macOS ARM64
        run: pnpm run build:mac
        env:
          ELECTRON_ARCH: ${{ matrix.arch }} # 传递架构给 Electron

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-build
          path: dist/

  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-arm64-build
          path: artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: artifacts/**/*
