name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-14
            artifact_name: mac-arm64
            arch: arm64
            build_script: build:mac
          - os: macos-14
            artifact_name: mac-intel
            arch: x64
            build_script: build:mac-x64
          # Windows 构建
          - os: windows-2022
            artifact_name: win-x64
            arch: x64
            build_script: build:win-x64

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          architecture: ${{ matrix.arch }}

      - name: Install dependencies
        run: pnpm install

      - name: Build for macOS ${{ matrix.arch }}
        run: pnpm run ${{ matrix.build_script }}
        env:
          ELECTRON_ARCH: ${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}-build
          path: |
            dist/**/*.dmg
            dist/**/*.exe

  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded artifacts (for debugging)
        run: ls -la artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            artifacts/**/*.dmg
            artifacts/**/*.exe
